name: build & release
on:
  push:
    branches:
      - beta

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create-release.outputs.result }}

    steps:
      - uses: actions/checkout@v3
       
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: get version
        id: version
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: get appname
        id: appname
        run: echo "APP_NAME=$(node -p "require('./package.json').name")" >> $GITHUB_ENV

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ process.env.APP_NAME }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  build-tauri:
  
    permissions:
      contents: write
    
    strategy:
      fail-fast: false
      matrix:
        targets:
          - platform: macos
            arch: x86_64-apple-darwin
          - platform: macos
            arch: aarch64-apple-darwin

          - platform: ubuntu
            arch: x86_64-unknown-linux-gnu
          - platform: ubuntu
            arch: aarch64-unknown-linux-gnu

          - platform: windows
            arch: x86_64-pc-windows-msvc
          - platform: windows
            arch: aarch64-pc-windows-msvc
            
    runs-on: ${{ matrix.targets.platform }}-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: npm
          
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.targets.arch }}
        
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
        
      - name: install dependencies (ubuntu only)
        if: matrix.targets.platform == 'ubuntu'
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      
      - name: installation modules nodejs
        run: npm install
        
      - name: vite build
        run : npx tauri build -t ${{ matrix.targets.arch }}
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ matrix.targets.platform }}-${{ matrix.targets.arch }}
          path: ./src-tauri/target/${{ matrix.targets.arch }}/release/bundle/
      
      - name: Release Linux
        uses: softprops/action-gh-release@v1
        if: matrix.targets.platform == 'ubuntu'
        with:
          files: |
            path: ./src-tauri/target/${{ matrix.targets.arch }}/release/bundle/appimage/*.AppImage
            path: ./src-tauri/target/${{ matrix.targets.arch }}/release/bundle/deb/*.deb
            
      - name: Release
        uses: softprops/action-gh-release@v1
        if: matrix.targets.platform == 'windows'
        with:
          files: |
            path: ./src-tauri/target/${{ matrix.targets.arch }}/release/bundle/msi/*.msi
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: matrix.targets.platform == 'macos'
        with:
          files: |
            path: ./src-tauri/target/${{ matrix.targets.arch }}/release/bundle/dmg/*.dmg
      
