name: build & release
on:
  push:
    branches:
      - beta

jobs:
  build-tauri:
    permissions:
      contents: write
      
    strategy:
      
      fail-fast: false
      matrix:
        targets:
          - platform: macos
            arch: x86_64-apple-darwin
          - platform: macos
            arch: aarch64-apple-darwin

          - platform: ubuntu
            arch: x86_64-unknown-linux-gnu
          - platform: ubuntu
            arch: aarch64-unknown-linux-gnu

          - platform: windows
            arch: x86_64-pc-windows-msvc
          - platform: windows
            arch: aarch64-pc-windows-msvc
            
    runs-on: ${{ matrix.targets.platform }}-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: npm
          
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.targets.arch }}
        
      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ./src-tauri
          key: ${{ matrix.targets.arch }}
        
      - name: install dependencies (ubuntu only)
        if: matrix.targets.platform == 'ubuntu'
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      
      - name: installation modules nodejs
        run: npm install
      
      - name: tauri build
        uses: liudonghua123/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseName: ${{ github.event.repository.name }} __VERSION__
          args: --target ${{ matrix.targets.arch }}
          tagName: build-__VERSION__
          target: ${{ matrix.target }}
