name: build & release
on:
  push:
    branches:
      - beta

jobs:
  build-tauri:
    permissions:
      contents: write
      
    strategy:
      
      fail-fast: false
      matrix:
        include:
          - os: macos
            target: x86_64-apple-darwin
          - os: macos
            target: aarch64-apple-darwin

          - os: ubuntu
            target: x86_64-unknown-linux-gnu
          - os: ubuntu
            target: aarch64-unknown-linux-gnu

          - os: windows
            target: x86_64-pc-windows-msvc
          - os: windows
            target: aarch64-pc-windows-msvc
            
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: npm
          
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.targets.arch }}
        
      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ./src-tauri
          key: ${{ matrix.targets.arch }}
        
      - name: install dependencies (ubuntu only)
        if: matrix.targets.platform == 'ubuntu'
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      
      - name: installation modules nodejs
        run: npm install
        
      - name: ls
        run: ls ./src-tauri/target
      
      - uses: liudonghua123/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "CyberChef v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          bundleIdentifier: app.cyberchef
          args: -t ${{ matrix.target }}
          target: ${{ matrix.target }}
