name: build test
on:
  pull_request:
    branches: "**"

jobs:
  build-tauri:
    permissions:
      contents: write
      
    strategy:
      
      fail-fast: false
      matrix:
        include:
          - os: macos
            target: x86_64-apple-darwin
          - os: macos
            target: aarch64-apple-darwin

          - os: ubuntu
            target: x86_64-unknown-linux-gnu
          - os: ubuntu
            target: aarch64-unknown-linux-gnu

          - os: windows
            target: x86_64-pc-windows-msvc
          - os: windows
            target: aarch64-pc-windows-msvc
            
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.target }}
      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ./src-tauri
            ./node_modules
            ~/.cargo
          key: ${{ matrix.target }}

      - uses: actions/checkout@v3
        
      - name: install dependencies (ubuntu only)
        if: matrix.os == 'ubuntu'
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      
      - name: setup for linux arm
        if: matrix.os == 'ubuntu' && matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo add-apt-repository universe
          sudo dpkg --add-architecture aarch64 
          sudo apt update
          sudo apt install -y \
            gcc-multilib \
            g++-multilib \
            libwebkit2gtk-4.0-dev:arm64 \
            libgtk-3-dev:arm64 \
            libssl-dev:arm64 \
            librsvg2-dev:arm64
          echo "PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
          echo "PKG_CONFIG_SYSROOT_DIR=/" >> $GITHUB_ENV
        
      - name: installation modules nodejs
        run: npm install

      - name: test build
        run: npm run build

      - name: test tauri build
        run: npx tauri build -t ${{ matrix.target }}
